<?php

/**
 * Implements hook_library().
 */
function uppod_library() {
  $libraries['uppod'] = array(
    'title' => 'Uppod Player',
    'website' => 'http://uppod.ru/player',
    'version' => '1.6.3',
    'js' => array(
      'https://ajax.googleapis.com/ajax/libs/swfobject/2.2/swfobject.js' => array(),
      libraries_get_path('uppod') . '/uppod.js' => array('preprocess' => FALSE),
      libraries_get_path('uppod') . '/uppod_api.js' => array('preprocess' => FALSE),
    ),
  );

  return $libraries;
}

/**
 * Implements hook_theme().
 */
function uppod_theme() {
  return array(
    'uppod' => array(
      'variables' => array(
        'file_object' => NULL,
        'preset' => '',
        'file_url' => '',
        'file_mime' => '',
        'options' => array(),
      ),
      'template' => 'theme/uppod',
    ),
  );
}

/**
 * Implements hook_field_formatter_info().
 */
function uppod_field_formatter_info() {
  $formatters = array(
    'uppod' => array(
      'label' => t('Uppod player'),
      'field types' => array('file', 'video'),
      'settings' => array(
        'uppod_preset' => '',
      ),
    ),
  );

  return $formatters;
}


/**
 * Implements hook_field_formatter_view().
 */
function uppod_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();

  if ($display['type'] == 'uppod') {
    // Process files for the theme function.
    $files = array();
    foreach ($items as $delta => $item) {
      $files[$delta] = (object) $item;
    }
    foreach ($files as $delta => $file) {
      $element[$delta] = array(
        '#theme' => 'uppod',
        '#file_object' => $file,
        '#preset' => $display['settings']['uppod_preset'],
      );
    }
  }

  return $element;
}

/**
 * Returns the default settings for Uppod Player. Used in cases where a preset is
 * not provided when the Uppod Player theme function is called.
 */
function uppod_default_settings() {
  $defaults = & drupal_static(__FUNCTION__);

  if (!isset($defaults)) {
    $defaults = array(
      'flashplayer' => file_create_url(libraries_get_path('uppod') . '/uppod.swf'),
      'width' => '480',
      'height' => '360',
      'autoplay' => FALSE,
    );
  }

  return $defaults;
}

/**
 * Implements hook_preprocess_HOOK().
 */
function uppod_preprocess_uppod(&$variables) {
  // If a file object has been passed grab the file URL and MIME from it,
  // but only if the values haven't already been set.
  if (isset($variables['file_object'])) {
    if (empty($variables['file_url'])) {
      $variables['file_url'] = file_create_url($variables['file_object']->uri);
    }
    if (empty($variables['file_mime'])) {
      $variables['file_mime'] = $variables['file_object']->filemime;
    }
    if (empty($variables['poster'])) {
      $variables['poster'] = file_create_url($variables['file_object']->thumbnailfile->uri);
    }
  }

  // Load defaults as the starting point.
  $default_settings = uppod_default_settings();

  // Get any preset override options that were sent through the formatter or
  // theme call.
  $options = array();
  if (isset($variables['options'])) {
    $options = $variables['options'];
    unset($variables['options']);
  }

  // Merge all variables together. Preset settings take priority over defaults,
  // variables passed directly to the theme function take priority over both.
  $variables = array_merge($default_settings, $options, $variables);

  $variables['html_id'] = 'uppod-' . md5(rand());

  // Create a configuration array which will be passed to Uppod's JavaScript.
  $variables['config'] = $default_settings;
  $variables['config']['file'] = $variables['file_url'];
  $variables['config']['poster'] = $variables['poster'];

  $variables['modes'] = array(
    'html5' => array('type' => 'html5'),
    'swf' => array(
      'type' => 'flash',
      'src' => file_create_url(libraries_get_path('uppod') . '/uppod.swf'),
    ),
  );
}

/**
 * Implements hook_process_HOOK().
 *
 * Add the Uppod Player Javascript according to the method selected.
 */
function uppod_process_uppod(&$variables) {
  drupal_add_library('uppod', 'uppod');
  drupal_add_js(array(
    'uppod' => array(
      $variables['html_id'] => $variables['config'],
      'modes' => $variables['modes'],
    )
  ), 'setting'); // Player settings
}
